### ISSUE TITLE
Error: Something went wrong when authenticating with the API.

### ISSUE THREAD

**Issue by wisentius** [MislavMandaric/home-assistant-vaillant-vsmart#10]
## Version of the custom_component

- 0097405, installed today (27/09/2021)

## Configuration

- Configuration was done via the GUI as described in the readme.

## Describe the bug

- When I try yo configure it (after install in HACS), I got the error:
  * Something went wrong when authenticating with the API. *

## Debug log

2021-09-27 11:37:56 ERROR (MainThread) [custom_components.vaillant_vsmart.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 283, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 154, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/vaillant_vsmart/config_flow.py", line 46, in async_step_user
    data = await self._get_config_storage_data(user_input)
  File "/config/custom_components/vaillant_vsmart/config_flow.py", line 106, in _get_config_storage_data
    token = await client.async_get_token(
  File "/usr/local/lib/python3.9/site-packages/vaillant_netatmo_api/auth.py", line 64, in async_get_token
    return await self._client.fetch_token(
  File "/usr/local/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 131, in _fetch_token
    resp = await self.post(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1807, in post
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 92, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1568, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1681, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 278, in handle_async_request
    (
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

```

**Comment by FabioEight** [comment]
Same here, HAOS last version:

`API communication exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 128, in handle_async_request
    ) = await self._receive_response(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 189, in _receive_response
    event = await self._receive_event(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 225, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 63, in read
    raise ReadTimeout from None
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/vaillant_vsmart/entity.py", line 59, in _update_method
    devices = await self._client.async_get_thermostats_data()
  File "/usr/local/lib/python3.9/site-packages/vaillant_netatmo_api/thermostat.py", line 73, in async_get_thermostats_data
    resp = await self._client.post(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1825, in post
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 92, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 276, in handle_async_request
    (
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout`

**Comment by MislavMandaric** [comment]
Hey, thanks for reporting the issue.

These are some networking issues, which I'm also seeing in my setup recently. I'm thinking it could be that the component is doing more requests than normal and the API is throttling it. But I'm not sure and next step for this component would be to add more detailed logging to help out.

After these logging improvements are released, I'll write an update here on the issue and ask you to repeat the setup process. Hopefully this will revel in more detail what is happening.

**Comment by MislavMandaric** [comment]
Today I released a new version of the underlying [library](https://github.com/MislavMandaric/vaillant-netatmo-api/releases/tag/v0.2.0) with the following improvements:

* Increased request timeout configuration from 5s to 15s
* Added retry logic to all requests
* Improved error handling and returning more detailed errors from the library

Next thing to do is to update the library in the component and actually log those more detailed errors in the integration. This, alongside increased timeouts and retry policy, should hopefully both reduce the errors you are seeing and improve the visibility of the errors if they continue happening.

I'll let you know when new version of the integration lands to test it out.

**Comment by wisentius** [comment]
Hello,

Hereby the requested info:

DOCKER OS:
----------
bash-5.1# cat /etc/issue 
Welcome to Alpine Linux 3.13
Kernel \r on an \m (\l)


HOST OS:
--------
support@datacollector01:~$ cat /etc/issue
Debian GNU/Linux 9 \n \l


SSL ON DOCKER:
-------------
bash-5.1# openssl
OpenSSL> version
OpenSSL 1.1.1k  25 Mar 2021


SSL ON HOST OS:
---------------
support@hassio01:~$ openssl
OpenSSL> version
OpenSSL 1.1.1d  10 Sep 2019


SSL ON HOME COMPUTER:
--------------------
support@datacollector01:~$ openssl
OpenSSL> version
OpenSSL 1.1.0f  25 May 2017


CURL ON HOME COMPUTER:
----------------------
support@datacollector01:~$ curl -v --request POST   --url https://api.netatmo.com/oauth2/token   --header 'Content-Type: application/x-www-form-urlencoded'   --data grant_type=password   --data username=xxxxx@gmail.com   --data password=xxxxxx   --data user_prefix=vaillant   --data app_version=1.0.4.0   --data client_id=na_client_android_vaillant   --data client_secret=xxxxxxx   --data '"scope=read_thermostat+write_thermostat"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 51.145.143.28...
* TCP_NODELAY set
* Connected to api.netatmo.com (51.145.143.28) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.netatmo.com
*  start date: Oct 16 20:10:59 2021 GMT
*  expire date: Nov 17 20:10:59 2022 GMT
*  subjectAltName: host "api.netatmo.com" matched cert's "*.netatmo.com"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> POST /oauth2/token HTTP/1.1
> Host: api.netatmo.com
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 237
> 
* upload completely sent off: 237 out of 237 bytes
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 21 Oct 2021 04:14:23 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-store
< X-XSS-Protection: 1; mode=block
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Powered-By: Netatmo
< 
* Curl_http_done: called premature == 0
* Connection #0 to host api.netatmo.com left intact
{"access_token":"60893cf156542f209732369c|4dd98e1ab7407c221736252a56bbc302","refresh_token":"60893cf156542f209732369c|8ba7e4f89943d45e5db311c4b790df35","scope":["all_scopes"],"expires_in":10800,"expire_in":10800}

**Comment by MislavMandaric** [comment]
Hey @wisentius.

Did you manage to get it to work?

From the log you posted and your setup, I'm fairly certain you have problems with the certificates and versions of OpenSSL. I suggest you try to check the official Docker Home Assistant images to see which versions they use and configuring your setup to use the same versions.

Unfortunately, I can't help you any further as I can't reproduce it on my setup and it would require too much time and effort to support all the various ways this component could be used (official and unofficial Docker images, HAOS, Supervised setup, virtualenv).
