### ISSUE TITLE
Continuous Disconections 

### ISSUE THREAD

**Issue by hu10gomm** [MislavMandaric/home-assistant-vaillant-vsmart#240]
Hello everyone, fist of all, thanks for your work and contribution.
-->

## Version of the custom_component -> 0.8.0 (the last one)

```yaml
![Register_1](https://user-images.githubusercontent.com/99735898/213688395-38d79fe5-75de-4542-a1c9-43360731fcea.PNG)
![Register_2](https://user-images.githubusercontent.com/99735898/213688398-d7b3f2d5-d297-4c6f-97a4-1723d5c6faa5.PNG)
![entities_picture](https://user-images.githubusercontent.com/99735898/213688399-00e97e33-b750-46dc-ac6a-b874d75bac09.PNG)

```

## Describe the bug

Continous Disconections. Every 6-10 minutes the entities became unavailable. Could you tell me how to repair it? I'm very interested that this add-on works properly.

## Debug log

Este error se originó a partir de una integración personalizada.

Logger: custom_components.vaillant_vsmart
Source: custom_components/vaillant_vsmart/entity.py:73
Integration: Vaillant vSMART (documentation, issues)
First occurred: 19 de enero de 2023, 08:14:47 (217 occurrences)
Last logged: 12:31:51

('Unknown network error while accessing the API. Retry the request or check the network if the issue persists.', {'method': 'POST', 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'device_type=NAVaillant&data_amount=app&sync_device_id=all&access_token=<FILTERED>&'}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 186, in connect_tcp
    addr_obj = ip_address(remote_host)
  File "/usr/local/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'api.netatmo.com' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 189, in connect_tcp
    gai_res = await getaddrinfo(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/errors.py", line 79, in client_error_handler
    yield
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/base.py", line 48, in _post
    resp = await self._client.post(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/vaillant_vsmart/entity.py", line 73, in _update_method
    devices = await self._client.async_get_thermostats_data()
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/thermostat.py", line 86, in async_get_thermostats_data
    body = await self._post(
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/base.py", line 47, in _post
    with client_error_handler():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/errors.py", line 83, in client_error_handler
    raise NetworkException("Unknown network error while accessing the API. Retry the request or check the network if the issue persists.", e.request, None) from e
vaillant_netatmo_api.errors.NetworkException: ('Unknown network error while accessing the API. Retry the request or check the network if the issue persists.', {'method': 'POST', 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'device_type=NAVaillant&data_amount=app&sync_device_id=all&access_token=<FILTERED>&'}, None)

**Comment by MislavMandaric** [comment]
Hi @hu10gomm.

This looks like some kind of networking error. More precisely, seems like DNS resolution fails for `api.netatmo.com`, which is out of scope of this integration. Can you please share your setup details?

1. Do you use Home Assistant OS, HA supervised, HA Container or HA Core?
2. What hardware, virtualization and OS are you using?
3. Are you using wired cable to connect HA instance to the router or WiFi? If it's WiFi, how far is the router?
4. Do you use a VPN or some custom DNS resolver?

TBH I don't think there is anything I can do, as this most certainly doesn't have anything to do with the integration, but is related to your setup. Keep in mind that this integration is more suspectable to networking issues as it's using cloud polling mechanism to fetch data, than something that works locally or is using a cloud push for getting data updates.
