### ISSUE TITLE
Error: Retrying setup: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ApolloF** [MislavMandaric/home-assistant-vaillant-vsmart#246]
Hi all, thanks for creating and supporting this integration. I would be very happy to get it working. I'm also an amateur, so maybe i did something wrong. 

## Configuration

```yaml
Client ID: na_client_android_vaillant
Client secret: 929XXXXX45f0
Username: XXXXX@gmail.com
Password: XXXXX
User prefix: vaillant
App Version: 1.0.4.0
```

## Describe the bug

The integration is installed via HACS. After filling in all the correct details, I get the 'Succes! Created configuration for XXXXX@gmail.com.' popup. After that it keeps giving the 'Retrying setup: 'NoneType' object cannot be interpreted as an integer' error.

## Debug log

```text
Logger: custom_components.vaillant_vsmart
Source: custom_components/vaillant_vsmart/entity.py:73
Integration: Vaillant vSMART ([documentation](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart), [issues](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/issues))
First occurred: February 2, 2023 at 11:40:12 PM (23 occurrences)
Last logged: February 2, 2023 at 11:59:46 PM
Unexpected error fetching vaillant_vsmart data: 'NoneType' object cannot be interpreted as an integer

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/vaillant_vsmart/entity.py", line 73, in _update_method
    devices = await self._client.async_get_thermostats_data()
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/thermostat.py", line 94, in async_get_thermostats_data
    return [Device(**device) for device in body["body"]["devices"]]
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/thermostat.py", line 94, in <listcomp>
    return [Device(**device) for device in body["body"]["devices"]]
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/thermostat.py", line 369, in __init__
    self.outdoor_temperature = OutdoorTemperature(**outdoor_temperature)
  File "/usr/local/lib/python3.10/site-packages/vaillant_netatmo_api/thermostat.py", line 593, in __init__
    self.ti = datetime.fromtimestamp(ti)
TypeError: 'NoneType' object cannot be interpreted as an integer


Logger: homeassistant.config_entries
Source: config_entries.py:900
First occurred: February 2, 2023 at 11:51:47 PM (1 occurrences)
Last logged: February 2, 2023 at 11:51:47 PM

Config entry 'XXXXX@gmail.com' for vaillant_vsmart integration not ready yet: 'NoneType' object cannot be interpreted as an integer; Retrying in background
```

**Comment by MislavMandaric** [comment]
Thank you for the nice bug report. I'll check it out and see what the issue is.

**Comment by ApolloF** [comment]
Fixed it. Needed to set my location in the Vaillant vSMART app: Settings> Information> Top right corner hamburger menu> Location.

Integration works wonderfully now.
