### ISSUE TITLE
"Integration requires reconfiguration" After restart always asking for credentials user/password only

### ISSUE THREAD

**Issue by bigtarget** [MislavMandaric/home-assistant-vaillant-vsmart#312]
Hello,

Thanks for all your work !!! It is working nice, but i have problem with expired session or something.

![obraz](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/assets/785445/79c50047-a98a-4658-829d-3ddae6757bee)
Of course after enter user and password all starting to work, but it is annoying to do it every day/restart.

Can you please check it?

**Comment by bigtarget** [comment]
More details:

Logger: custom_components.vaillant_vsmart
Source: helpers/update_coordinator.py:366
Integration: Vaillant vSMART ([documentation](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart), [issues](https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/issues))
First occurred: 09:46:16 (1 occurrences)
Last logged: 09:46:16
Authentication failed while fetching vaillant_vsmart data: ('Access token is invalid or expired. Refresh the access token and try again.', {'method': 'POST', 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'device_type=NAVaillant&data_amount=app&sync_device_id=all&access_token=<FILTERED>&'}, {'status_code': 403, 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'{"error":{"code":2,"message":"Invalid access token"}}', 'duration': datetime.timedelta(microseconds=77999)})

**Comment by bigtarget** [comment]
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.vaillant_vsmart.config_flow
Source: custom_components/vaillant_vsmart/config_flow.py:65
Integration: Vaillant vSMART (documentation, issues)
First occurred: 09:46:16 (1 occurrences)
Last logged: 09:46:16

("Server processed the request and returned a 4xx response. Don't retry the request without changing the arguments as the new request will fail again with the same error.", {'method': 'POST', 'url': URL('https://api.netatmo.com/oauth2/token'), 'body': b'username=&password=<FILTERED>&app_version=1.0.4.0&grant_type=password&client_id=na_client_android_vaillant&client_secret=929a9f6253babbee1a6e8d4bd51745f0&scope=read_thermostat+write_thermostat'}, {'status_code': 400, 'url': URL('https://api.netatmo.com/oauth2/token'), 'body': b'{"error":"invalid_request","error_description":"Missing parameters, \\"username\\" and \\"password\\" are required"}', 'duration': datetime.timedelta(microseconds=59633)})
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/vaillant_netatmo_api/errors.py", line 79, in client_error_handler
    yield
  File "/usr/local/lib/python3.12/site-packages/vaillant_netatmo_api/base.py", line 55, in _post
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 ' for url 'https://api.netatmo.com/oauth2/token'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/vaillant_vsmart/config_flow.py", line 65, in _async_step_all
    data = await self._get_config_storage_data(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vaillant_vsmart/config_flow.py", line 155, in _get_config_storage_data
    await client.async_token(
  File "/usr/local/lib/python3.12/site-packages/vaillant_netatmo_api/auth.py", line 74, in async_token
    body = await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vaillant_netatmo_api/base.py", line 47, in _post
    with client_error_handler():
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/vaillant_netatmo_api/errors.py", line 90, in client_error_handler
    raise RequestClientException("Server processed the request and returned a 4xx response. Don't retry the request without changing the arguments as the new request will fail again with the same error.", e.request, e.response) from e
vaillant_netatmo_api.errors.RequestClientException: ("Server processed the request and returned a 4xx response. Don't retry the request without changing the arguments as the new request will fail again with the same error.", {'method': 'POST', 'url': URL('https://api.netatmo.com/oauth2/token'), 'body': b'username=&password=<FILTERED>&app_version=1.0.4.0&grant_type=password&client_id=na_client_android_vaillant&client_secret=929a9f6253babbee1a6e8d4bd51745f0&scope=read_thermostat+write_thermostat'}, {'status_code': 400, 'url': URL('https://api.netatmo.com/oauth2/token'), 'body': b'{"error":"invalid_request","error_description":"Missing parameters, \\"username\\" and \\"password\\" are required"}', 'duration': datetime.timedelta(microseconds=59633)})

**Comment by bigtarget** [comment]
I am using all latest: v.0.9.0 and  
HA 
Core 2024.2.0
Supervisor 2024.01.1
Operating System 11.5
Interfejs użytkownika 20240207.0

**Comment by liberatofiasca** [comment]
Same problem here, starting from february 2024 versions and above.

**Comment by MislavMandaric** [comment]
I'm sorry to hear that you have issues with the integration. I tried reproducing this, but I can't. I don't have any disconnects and I get reauth request almost exclusively after I work on this locally, thus generating a lot of tokens, making them invalid. Other than that, I don't get any issues.

**Comment by toniaisense** [comment]
Dear @MislavMandaric,

I am experiencing the same problem; the Vaillant system disconnects approximately every half hour.

Here is the error I receive:

![prtscr](https://github.com/user-attachments/assets/61c6943f-4ca3-4bfa-8070-c2f45aa40641)

These are my settings:

![image](https://github.com/user-attachments/assets/a440c4f9-4fac-4fe4-8a46-a355bd8aa03f)

When I re-add the system, everything works fine for a short time, but then the issue recurs.

Could you kindly advise on how to resolve this?

Thank you for your excellent work and assistance!

Best regards,
Toni

**Comment by GDefina** [comment]
> I'm sorry to hear that you have issues with the integration. I tried reproducing this, but I can't. I don't have any disconnects and I get reauth request almost exclusively after I work on this locally, thus generating a lot of tokens, making them invalid. Other than that, I don't get any issues.

Hi Mislav,
I have the same problem too.
I tried uninstalling and reinstalling, but it didn't work.
It seems that I can't save the credentials and that at each session I need to re-authenticate... so this integration is not usable... can we provide you with some more information to debug?

Thanks for your support.

**Comment by GDefina** [comment]
Update... i find this in my log:

2024-12-17 17:58:54.589 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'vaillant_vsmart' creates a new entry in a 'reauth' flow, when it is expected to update an existing entry and abort at custom_components/vaillant_vsmart/config_flow.py, line 85: return self.async_create_entry(title=user_input[CONF_USERNAME], data=data). **This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/issues**

**Comment by GDefina** [comment]
This solution **not working** for me:

![image](https://github.com/user-attachments/assets/11a15e21-d9cd-4a52-9311-4a3f7c4b4c8b)

source: https://githubhelp.com/MislavMandaric/home-assistant-vaillant-vsmart

**Comment by GitStijn** [comment]
Still faling thuis issue in latent version of HA and the integration.
Also found something about new terms that needed to be approved on the vaillant site, so i did the change country and back but didn’t make anything change. 

Anyone having and luck on this?
