### ISSUE TITLE
Inegration get 5xx error back

### ISSUE THREAD

**Issue by xvisionbelgium** [MislavMandaric/home-assistant-vaillant-vsmart#408]
Since a couple of days the Valliant integration gets a 5xx error back.
Nothing changed on our configuration end. I even delete the config and reconfigured it from scratch.
I'm using it with a MiGO/Bulex

Any idea what is going on ? Worked flawlessly for months....

Error Reported:
2024-12-16 12:52:39.379 ERROR (MainThread) [custom_components.vaillant_vsmart] ("Server couldn't process the request successfully and returned a 5xx response. Try again with reasonable backoff strategy.", {'method': 'POST', 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'device_type=NAVaillant&data_amount=app&sync_device_id=all&access_token=<FILTERED>&'}, {'status_code': 500, 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'{"error":{"code":500,"message":"Internal Server Error"}}', 'duration': datetime.timedelta(microseconds=60649)})
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/vaillant_netatmo_api/errors.py", line 79, in client_error_handler
    yield
  File "/usr/local/lib/python3.13/site-packages/vaillant_netatmo_api/base.py", line 56, in _post
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://api.netatmo.com/api/getthermostatsdata'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/vaillant_vsmart/entity.py", line 77, in _update_method
    devices = await self._client.async_get_thermostats_data()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/vaillant_netatmo_api/thermostat.py", line 86, in async_get_thermostats_data
    body = await self._post(
           ^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/vaillant_netatmo_api/base.py", line 47, in _post
    with client_error_handler():
         ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/vaillant_netatmo_api/errors.py", line 92, in client_error_handler
    raise RequestServerException("Server couldn't process the request successfully and returned a 5xx response. Try again with reasonable backoff strategy.", e.request, e.response) from e
vaillant_netatmo_api.errors.RequestServerException: ("Server couldn't process the request successfully and returned a 5xx response. Try again with reasonable backoff strategy.", {'method': 'POST', 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'device_type=NAVaillant&data_amount=app&sync_device_id=all&access_token=&'}, {'status_code': 500, 'url': URL('https://api.netatmo.com/api/getthermostatsdata'), 'body': b'{"error":{"code":500,"message":"Internal Server Error"}}', 'duration': datetime.timedelta(microseconds=60649)})

**Comment by xvisionbelgium** [comment]
Can somebody help ? Tried today to reconfigure again, still the same error response.

**Comment by peter1rhodes** [comment]
I've just started to get the same problem, quite abruptly. I've no idea what caused it, it appears to have happened a few minutes ago. In my case, it's a 504 Gateway Timeout, but the eRelax app is working OK
