### ISSUE TITLE
Unavailable with latest version og HA 2022.4.0

### ISSUE THREAD

**Issue by KnNLmS** [MislavMandaric/home-assistant-vaillant-vsmart#90]
Erelax/Vsmart device is unavailable after upgrade to the 2022.4.0

**Comment by JensVanhooydonck** [comment]
Error log:
```
Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:529
Integration: Switch (documentation, issues)
First occurred: 9:19:17 PM (2 occurrences)
Last logged: 9:19:17 PM

Error adding entities for domain switch with platform vaillant_vsmart
Error while setting up vaillant_vsmart platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

```

**Comment by Devenda** [comment]
Same issue here, but strangely the thermostat in HA is still working.
The battery indicator, however, is not:

![Screenshot_20220407-152735](https://user-images.githubusercontent.com/2527506/162209876-73a8c3c7-26c7-4305-b3f4-94fd888a10a7.png)

**Comment by DarkShadowNight** [comment]
Same here

**Comment by MislavMandaric** [comment]
Thank you for reporting the issue.

I'll look into it and post here when the fix is ready.

**Comment by MislavMandaric** [comment]
The fix is up and you can update through HACS.
